repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Use the latest version of Flake8
    hooks:
      - id: flake8
        args: [--max-line-length=128]  # Example argument
        exclude: ^\.cache/

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.3  # Use the latest version of autopep8
    hooks:
      - id: autopep8
        args: ["--in-place", "--aggressive", "--aggressive"]
        exclude: ^\.cache/
        additional_dependencies:
          - packaging
